#GAME SETTINGS
TILESIZE = 50
ROWS = 20
COLUMNS = 20
NUM_MINES= 50
WIDTH = ROWS * TILESIZE
HEIGHT = COLUMNS * TILESIZE
TITLE = "Minesweeper"
FPS = 60
#COLORS (r,g,b)
BACKGROUND_COLOR = (0,200,0)

#MOUSE SETTINGS
XCENTER= 1920//2
YCENTER = 1080//2
XMIN=XCENTER-WIDTH
XMAX=XCENTER+WIDTH
YMIN=YCENTER-HEIGHT
YMAX=YCENTER+HEIGHT